/*
 * DIO_Expander_Config.h
 *
 *  Created on: Jun 4, 2023
 *      Author: Mohamed Nasser
 */

#include"DIO_Interface.h"
#include"DIO_Expander_Private.h"

#ifndef I_O_INTERFACE_HEADER_FILES_DIO_EXPANDER_CONFIG_H_
#define I_O_INTERFACE_HEADER_FILES_DIO_EXPANDER_CONFIG_H_

#define DIO_Expander_INPUT_FLOAT 		INPUT_FLOATING
#define DIO_Expander_INPUT_PULL_UP 		PULL_UP
#define DIO_Expander_INPUT_PULL_DOWN 	PULL_DOWN
#define DIO_Expander_OUPUT  			OUTPUT_SPEED_2MHZ_PP
#define DIO_Expander_Open_Drain         OUTPUT_SPEED_2MHZ_OD

#define DIO_Expander_HIGH				GPIO_HIGH
#define DIO_Expander_LOW				GPIO_LOW

#define EXPANDER_OUTPUT   0
#define EXPANDER_INPUT    1
#define EXPANDER_ENABLE   1
#define EXPANDER_DISABLE  0

#define DIO_EXPANDER_PIN_0		DIO_EXPANDER_PIN0
#define DIO_EXPANDER_PIN_1		DIO_EXPANDER_PIN1
#define DIO_EXPANDER_PIN_2		DIO_EXPANDER_PIN2
#define DIO_EXPANDER_PIN_3		DIO_EXPANDER_PIN3
#define DIO_EXPANDER_PIN_8		DIO_EXPANDER_PIN8
#define DIO_EXPANDER_PIN_9		DIO_EXPANDER_PIN9
#define DIO_EXPANDER_PIN_10		DIO_EXPANDER_PIN10
#define DIO_EXPANDER_PIN_11		DIO_EXPANDER_PIN11



#define DIO_EXPANDER_PIN_4 		DIO_EXPANDER_PIN4
#define DIO_EXPANDER_PIN_5 		DIO_EXPANDER_PIN5
#define DIO_EXPANDER_PIN_6 		DIO_EXPANDER_PIN6
#define DIO_EXPANDER_PIN_7 		DIO_EXPANDER_PIN7

#define DIO_EXPANDER_PIN_15		DIO_EXPANDER_PIN15
#define DIO_EXPANDER_PIN_14		DIO_EXPANDER_PIN14
#define DIO_EXPANDER_PIN_13		DIO_EXPANDER_PIN13
#define DIO_EXPANDER_PIN_12		DIO_EXPANDER_PIN12
#endif /* I_O_INTERFACE_HEADER_FILES_DIO_EXPANDER_CONFIG_H_ */

