#ifndef	OBJECT_CONFIG_H
#define	OBJECT_CONFIG_H

#define OBJECT_NO_ON_SYSTEM_50	50
#define OBJECT_WIFI_ID_50		1
#define OBJECT_RELAY_OUTPUT_50	PIN_6
#define OBJECT_SWITCH_INPUT_50	PIN_20
#define OBJECT_TURN_OFF_TIME_50	0

#define OBJECT_NO_ON_SYSTEM_51	51
#define OBJECT_WIFI_ID_51		2
#define OBJECT_RELAY_OUTPUT_51	PIN_7
#define OBJECT_SWITCH_INPUT_51	PIN_21
#define OBJECT_TURN_OFF_TIME_51	0

#define OBJECT_NO_ON_SYSTEM_52	52
#define OBJECT_WIFI_ID_52		3
#define OBJECT_RELAY_OUTPUT_52	PIN_8
#define OBJECT_SWITCH_INPUT_52	PIN_22
#define OBJECT_TURN_OFF_TIME_52	10

#define OBJECT_NO_ON_SYSTEM_53	53
#define OBJECT_WIFI_ID_53		4
#define OBJECT_RELAY_OUTPUT_53	PIN_9
#define OBJECT_SWITCH_INPUT_53	PIN_23
#define OBJECT_TURN_OFF_TIME_53	30

#define OBJECT_CONFIG_NUMBERS	4
#endif