#ifndef	OBJECT_CONFIG_H
#define	OBJECT_CONFIG_H

#define OBJECT_NO_ON_SYSTEM_1	1
#define OBJECT_WIFI_ID_1		1
#define OBJECT_RELAY_OUTPUT_1	PIN_6
#define OBJECT_SWITCH_INPUT_1	PIN_7
#define OBJECT_TURN_OFF_TIME_1	0

#define OBJECT_NO_ON_SYSTEM_2	2
#define OBJECT_WIFI_ID_2		2
#define OBJECT_RELAY_OUTPUT_2	PIN_8
#define OBJECT_SWITCH_INPUT_2	PIN_9
#define OBJECT_TURN_OFF_TIME_2	0

#define OBJECT_NO_ON_SYSTEM_3	3
#define OBJECT_WIFI_ID_3		3
#define OBJECT_RELAY_OUTPUT_3	PIN_10
#define OBJECT_SWITCH_INPUT_3	PIN_11
#define OBJECT_TURN_OFF_TIME_3	0

#define OBJECT_NO_ON_SYSTEM_4	4
#define OBJECT_WIFI_ID_4		4
#define OBJECT_RELAY_OUTPUT_4	PIN_12
#define OBJECT_SWITCH_INPUT_4	PIN_13
#define OBJECT_TURN_OFF_TIME_4	0

#define OBJECT_CONFIG_NUMBERS	4
#endif