#ifndef	OBJECT_CONFIG_H
#define	OBJECT_CONFIG_H

#define OBJECT_NO_ON_SYSTEM_50	50
#define OBJECT_WIFI_ID_50		1
#define OBJECT_RELAY_OUTPUT_50	PIN_6
#define OBJECT_SWITCH_INPUT_50	PIN_10
#define OBJECT_TURN_OFF_TIME_50	5

#define OBJECT_NO_ON_SYSTEM_51	51
#define OBJECT_WIFI_ID_51		2
#define OBJECT_RELAY_OUTPUT_51	PIN_7
#define OBJECT_SWITCH_INPUT_51	PIN_11
#define OBJECT_TURN_OFF_TIME_51	0

#define OBJECT_NO_ON_SYSTEM_52	52
#define OBJECT_WIFI_ID_52		3
#define OBJECT_RELAY_OUTPUT_52	PIN_8
#define OBJECT_SWITCH_INPUT_52	PIN_12
#define OBJECT_TURN_OFF_TIME_52	0

#define OBJECT_NO_ON_SYSTEM_53	53
#define OBJECT_WIFI_ID_53		4
#define OBJECT_RELAY_OUTPUT_53	PIN_9
#define OBJECT_SWITCH_INPUT_53	PIN_13
#define OBJECT_TURN_OFF_TIME_53	0

#define OBJECT_NO_ON_SYSTEM_54	54
#define OBJECT_WIFI_ID_54		5
#define OBJECT_RELAY_OUTPUT_54	PIN_0
#define OBJECT_SWITCH_INPUT_54	PIN_3
#define OBJECT_TURN_OFF_TIME_54	0

#define OBJECT_NO_ON_SYSTEM_55	55
#define OBJECT_WIFI_ID_55		6
#define OBJECT_RELAY_OUTPUT_55	PIN_1
#define OBJECT_SWITCH_INPUT_55	PIN_4
#define OBJECT_TURN_OFF_TIME_55	0

#define OBJECT_NO_ON_SYSTEM_56	56
#define OBJECT_WIFI_ID_56		7
#define OBJECT_RELAY_OUTPUT_56	PIN_2
#define OBJECT_SWITCH_INPUT_56	PIN_5
#define OBJECT_TURN_OFF_TIME_56	0

#define OBJECT_CONFIG_NUMBERS	7
#endif
